### ISSUE TITLE
Lang strings missing

### ISSUE THREAD

**Issue by Reconix** [dansanti/flexi-auth#6]
Not sure who but someone was nice enough to add half the language options into the demo views but didn't update the corresponding flexi_auth_lang.php file.

I've started to create them but my god is there a lot...

If you happen to have this file it'd be awesome,

**Comment by dansanti** [comment]
Hi! await till tomorrow, I have many translate string, but need order it.

I'll  commit tomorrow, and I think, upload a simple hook, to switch between language , like my demo page.
